### ISSUE TITLE
open vim in nvim terminal will causing error

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#668] opened 2023-04-19 08:11 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.0

### Operating system/version

macOS 13.2.1

### Terminal name/version

Warp

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. open terminal in nvim using M-d (floating terminal) or vertical or horizontal
2. open vim in terminal
3. before vim open, some error will print

### Expected behavior

no error should print before open vim

### Actual behavior

error printed before open vim:
```
> vim
Error detected while processing /Users/saafo/.vimrc[2]../opt/homebrew/Cellar/neovim/0.9.0/share/nvim/runtime/s
yntax/syntax.vim:
line   43:
E216: No such group or event: filetypedetect BufRead
Error detected while processing /opt/homebrew/Cellar/neovim/0.9.0/share/nvim/runtime/plugin/rplugin.vim[66]..f
unction <SNR>13_LoadRemotePlugins[1]..<SNR>13_GetManifest[1]..<SNR>13_GetManifestPath:
line    7:
E117: Unknown function: stdpath
Press ENTER or type command to continue
```

**Comment by CharlesChiuGit** [comment] 2023-04-19 08:22
Can u reproduce it on other terminal emulator?

**Comment by Saafo** [comment] 2023-04-19 08:26
@CharlesChiuGit Yes, I can reproduce it on iTerm2

**Comment by CharlesChiuGit** [comment] 2023-04-19 08:31
This is very weird, `BufRead` autocmd is in the doc for a very long time. I think sth is wrong with the nvim u use. 
How did u install nvim 0.9?

**Comment by Saafo** [comment] 2023-04-19 08:40
Well, I install and upgrade neovim through brew.

**Comment by Saafo** [comment] 2023-04-19 08:42
I revert all my changes in local (reset to current main branch), and the problem still exist

**Comment by CharlesChiuGit** [comment] 2023-04-19 08:43
Can u try this version? 
https://github.com/neovim/neovim/releases/tag/stable

**Comment by Saafo** [comment] 2023-04-19 08:46
Yes I'm currently using this version. Do you mean I should uninstall nvim and install it through this way?

```
Download nvim-macos.tar.gz
Run xattr -c ./nvim-macos.tar.gz (to avoid "unknown developer" warning)
Extract: tar xzvf nvim-macos.tar.gz
Run ./nvim-macos/bin/nvim
```

**Comment by CharlesChiuGit** [comment] 2023-04-19 08:47
ys!

**Comment by Saafo** [comment] 2023-04-19 08:57
I run `./nvim-macos/bin/nvim` and still can reproduce...

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:01
wait, u mean u want to open `vim` inside on `nvim`?

**Comment by Saafo** [comment] 2023-04-19 09:02
I'm not sure whether it's related to my .vimrc, since I delete my .vimrc, the error message changed:

```
❯ vim
E1187: Failed to source defaults.vim
Error detected while processing /Users/saafo/Downloads/nvim-macos/share/nvim/runtime/plugin/rplugin.vim[66]..f
unction <SNR>9_LoadRemotePlugins[1]..<SNR>9_GetManifest[1]..<SNR>9_GetManifestPath:
line    7:
E117: Unknown function: stdpath
--- Autocommands ---
Error detected while processing /Users/saafo/Downloads/nvim-macos/share/nvim/runtime/plugin/shada.vim:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   20:
E35: No previous regular expression
line   21:
E10: \ should be followed by /, ? or &
line   22:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   24:
E10: \ should be followed by /, ? or &
line   25:
E10: \ should be followed by /, ? or &
line   26:
E10: \ should be followed by /, ? or &
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
line   29:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   31:
E10: \ should be followed by /, ? or &
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
E10: \ should be followed by /, ? or &
line   35:
E10: \ should be followed by /, ? or &
line   36:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   38:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue

```

my original .vimrc:

```
set nocompatible
syntax on
set showmode
set laststatus=2
set showcmd
set mouse=a
set encoding=utf-8
set t_Co=256
filetype indent on

set autoindent
set tabstop=2
set shiftwidth=4
set expandtab
set softtabstop=2

set number
set cursorline
set textwidth=120
set wrap
set linebreak
set wrapmargin=2
set scrolloff=3
set sidescrolloff=5
set ruler

set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase

set visualbell
set autoread
set listchars=tab:»■,trail:■
set list

set wildmenu
set wildmode=longest:list,full

if has('clipboard')
    if has('unnamedplus')  " When possible use + register for copy-paste
        set clipboard=unnamed,unnamedplus
    else         " On mac and Windows, use * register for copy-paste
        set clipboard=unnamed
    endif
endif

```

**Comment by Saafo** [comment] 2023-04-19 09:02
> wait, u mean u want to open `vim` inside on `nvim`'s term mode?

Yes exactly! open `vim` in `nvim`'s emulate terminal

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:03
Can reproduce in ubuntu22.04.
![圖片](https://user-images.githubusercontent.com/32497323/233025208-483a33da-59ac-4965-ab14-610a72046024.png)

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:10
I think this is basically impossible to do. It's not a nvim config issue.
I tried with `nvim --clean` and the result is still the same.
So I think using vim inside nvim is forbidden by god.
But u can use nested nvim if u know how to use [rpc](https://neovim.io/doc/user/api.html) correctly.

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:14
Fell free to comment if u have some new insights!

**Comment by Jint-lzxy** [comment] 2023-04-19 09:18
This is expected, since `$VIMRUNTIME` is set to Neovim's runtime. Please unset it before running vim in `:terminal`.

**Comment by Saafo** [comment] 2023-04-19 09:20
I argue this problem because I use Lazygit in `nvim`'s terminal, and when I wrote commit message, it will open editor.

I'll try to set editor env to nvim to avoid open vim in nvim.

**Comment by Jint-lzxy** [comment] 2023-04-19 09:22
> I argue this problem because I use Lazygit in `nvim`'s terminal, and when I wrote commit message, it will open editor.
> 
> I'll try to set `$EDITOR` env to nvim to avoid open vim in nvim.

Yep this will do the trick 👍

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:23
> This is expected, since `$VIMRUNTIME` is set to Neovim's runtime. Please unset it before running vim in `:terminal`. Remember that `vim` and `nvim` share the vast majority of options.
> 
> cc @Saafo @CharlesChiuGit

![圖片](https://user-images.githubusercontent.com/32497323/233030760-5e638dba-97cc-4248-a685-fd5bb4b1c745.png)

No luck for me. QAQ

**Comment by Jint-lzxy** [comment] 2023-04-19 09:24
@CharlesChiuGit u need to set `VIMRUNTIME=vim` 😄

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:26
![圖片](https://user-images.githubusercontent.com/32497323/233031583-ff16f731-775e-449c-ae8c-ab6623f1a32f.png)
![圖片](https://user-images.githubusercontent.com/32497323/233031624-201fed1d-2d1a-47aa-a615-36d413ba77dc.png)
![圖片](https://user-images.githubusercontent.com/32497323/233031678-0423fb3d-543f-4267-937f-d01fabb11645.png)

**Comment by Jint-lzxy** [comment] 2023-04-19 09:29
Looks like you need to manually specify rtp for vim:
```sh
export VIMRUNTIME=/usr/share/vim/vim90 # replace this with your vim rtp
unset VIM
```

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:33
![圖片](https://user-images.githubusercontent.com/32497323/233033288-017cfa70-f96b-4438-8878-8b83c17a2f5d.png)

It can enter vim after pressing `enter`, but it's too much work to do lol

**Comment by CharlesChiuGit** [comment] 2023-04-19 09:37
> 

That's what i did too lol

**Comment by Jint-lzxy** [comment] 2023-04-19 09:39
> It can enter vim after pressing `enter`, but it's too much work to do lol

Yep `nvim -u ~/.config/nvim/init.vim` would suffice if the user insists on wanting `vim`'s behavior.

**Comment by Jint-lzxy** [comment] 2023-04-19 09:40
> It can enter vim after pressing `enter`, but it's too much work to do lol

Yep `nvim -u ~/.config/nvim/init.vim` would suffice if the user insists on wanting `vim`'s behavior lol

**Comment by Jint-lzxy** [comment] 2023-04-19 11:24
Closing as the original issue has been resolved.

**Closed by Jint-lzxy** 2023-04-19 11:24 UTC
Labels: usage, env
