### ISSUE TITLE
Install script abort when turn off shallow clone

### ISSUE THREAD

**Issue by FangLin2001** [ayamir/nvimdots#674] opened 2023-04-21 03:03 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

be set as backup by install script

### Operating system/version

Win10 22H2 19045.2846

### Terminal name/version

None

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Just run the install script in PowerShell 7
```
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.ps1'))
```
select No as 'git clone' preferences

### Expected behavior

set 'git clone' preferences correctly

### Actual behavior

_abort -Msg "Failed during: $WithCmd" -Type "InvalidResult"
![image](https://user-images.githubusercontent.com/50603032/233529597-615b9efa-c89a-41b6-9530-6fed22c869b7.png)

### Additional information

I encountered tons of errors when executing the install script, most of which disappeared after repeated execution and manual installation of dependencies.

**Comment by CharlesChiuGit** [comment] 2023-04-21 03:08
i guess a lot of your programs are out-ot-date? maybe try update those programs first?

run: "winget update --all"

**Comment by CharlesChiuGit** [comment] 2023-04-21 03:15
Also I suspect u didn't config your git -> github properly. did u choose `ssh install` instead of `https install`?

**Comment by ayamir** [comment] 2023-04-21 04:33
Yes, I can confirm it before, but I forgot to report it.

**Comment by CharlesChiuGit** [comment] 2023-04-21 04:42
hmmm, but i never ran into this error, no matter I choose shallow clone for not.

**Comment by CharlesChiuGit** [comment] 2023-04-21 04:50
from the install.ps1, it's using https to clone this repo, maybe it have some proxy issues?

**Comment by CharlesChiuGit** [comment] 2023-04-21 04:52
@FangLin2001 @ayamir can u check if cloning this repo via https works on windows?

**Comment by CharlesChiuGit** [comment] 2023-04-21 04:57
side note: @Jint-lzxy i have an idea, can we query the branch tags and let users decide which branch they want to install?

**Comment by FangLin2001** [comment] 2023-04-21 05:16
> i guess a lot of your programs are out-ot-date? maybe try update those programs first? (git for example)
> 
> run: `winget update --all`

> Also I suspect u didn't config your git -> github properly. did u choose `ssh install` instead of `https install`?

Nothing better after i update a particular WindowsSDK and i make sure my git works well. I can git fetch/clone any other repo.

> @FangLin2001 @ayamir can u check if directly cloning this repo via https works on windows with terminal proxies configed?

It's OK to git clone https://github.com/ayamir/nvimdots.git in my device, btw i keep FastGithub running throughtout the installation. (https://github.com/dotnetcore/FastGithub)
But now i encounter npm UNABLE_TO_VERIFY_LEAF_SIGNATURE error again and this problem seems only depend on net condition. God bless it would be fine somehow.

**Comment by CharlesChiuGit** [comment] 2023-04-21 05:25
> But now i encounter npm UNABLE_TO_VERIFY_LEAF_SIGNATURE error again and this problem seems only depend on net condition. God bless it would be fine somehow.

try this: `npm config set strict-ssl false`

**Comment by CharlesChiuGit** [comment] 2023-04-21 05:25
> Maybe using VSCode is the final solution.

:pleading_face::pleading_face::pleading_face:

**Comment by FangLin2001** [comment] 2023-04-21 05:35
> try this: `npm config set strict-ssl false`

Already tried and not works. But NodeJS dependency check have worked well and done in one of my attempts.
Still error in git clone preference setting.

**Comment by CharlesChiuGit** [comment] 2023-04-21 05:44
I still think it's related to the GFW, since I never ran into errors like this. (based in Taiwan)

But I often encounters errors while installing the nvim plugins, but I don't think it's related to the installation script. It's properly `lazy.nvim`'s issue. I need to manually delete the plugins and let it re-install again often times.

**Comment by FangLin2001** [comment] 2023-04-21 07:43
Although I still encounter npm UNABLE_TO_VERIFY_LEAF_SIGNATURE error in NodeJS dependencies check, as i have done it correctly somehow before, i ignore it and select Yes in git clone preference (still error with No). And most of things seems OK if ignoring errors generated by some plugins. Thanks a lot.
Btw, using rsa key with not-empty passphrase would cause git permission deny when cloning lazy at startup.

**Comment by Jint-lzxy** [comment] 2023-04-21 07:59
Can reproduce under specific conditions _(sometimes script blocks \[used by `safe_execute`\] are not parsed properly, i.e., characters are escaped)_. Will push a patch asap.

As for the dependency installation issue, _probably_ that is caused by accessing a source through a proxy and the proxy returned a corrupted (or empty) CA Certificate. Will look into this after the first issue is addressed.

@FangLin2001 Will the following code block raise the same issue on your device?
```pwsh
function safe_execute ([Parameter(Mandatory = $True)][ValidateNotNullOrEmpty()] [scriptblock]$WithCmd) {
	try {
		Invoke-Command -ErrorAction Stop -ScriptBlock $WithCmd
		if (-not $?) {
			throw
		}
	}
	catch {
		_abort -Msg "Failed during: $WithCmd" -Type "InvalidResult"
	}
}

$env:CCLONE_ATTR = ''
safe_execute -WithCmd { git clone --progress -b main "$env:CCLONE_ATTR" 'git@github.com:ayamir/nvimdots.git' }
```

**Comment by Jint-lzxy** [comment] 2023-04-21 08:03
Can reproduce under specific conditions _(sometimes script blocks \[used by `safe_execute`\] are not parsed properly, i.e., characters are escaped)_. Will push a patch asap.

As for the dependency installation issue, _probably_ that is caused by accessing a source through a proxy and the proxy returned a corrupted (or empty) CA Certificate. Will look into this after the first issue is addressed.

@FangLin2001 Will the following code block raise the same issue on your device?
```pwsh
$env:CCLONE_ATTR = ''

try {
	Invoke-Command -ErrorAction Stop -ScriptBlock { git clone --progress -b main "$env:CCLONE_ATTR" 'https://github.com/ayamir/nvimdots.git' }
	if (-not $?) {
		throw
	}
}
catch {
	Write-Error -Message "Command failed." -Category "InvalidResult"
}
```

**Comment by Jint-lzxy** [comment] 2023-04-21 08:18
> i have an idea, can we live query the branch tags and let users decide which branch they want to install?

Hmm but I can't think of a reason why we should implement this - FWIW branch detection based on `nvim --version` would suffice.

In fact, if ppl really want to customize their clone branch, `CCLONE_BRANCH` is reserved as a global option for them 😄
https://github.com/ayamir/nvimdots/blob/f1c5f091c5f4fd8d41c92d29085f96984ba1aebb/scripts/install.ps1#L22

cc @CharlesChiuGit

**Comment by Jint-lzxy** [comment] 2023-04-21 08:23
> Btw, using rsa key with not-empty passphrase would cause git permission deny when cloning lazy at startup.

This is expected. Since you need to instruct `ssh-agent` to store your password in memory after each startup. FYI:
- https://unix.stackexchange.com/a/90869
- https://man.openbsd.org/ssh_config.5#AddKeysToAgent

**Comment by FangLin2001** [comment] 2023-04-21 08:27
> @FangLin2001 Will the following code block raise the same issue on your device?
> 
> ```powershell
> $env:CCLONE_ATTR = ''
> 
> try {
> 	Invoke-Command -ErrorAction Stop -ScriptBlock { git clone --progress -b main "$env:CCLONE_ATTR" 'https://github.com/ayamir/nvimdots.git' }
> 	if (-not $?) {
> 		throw
> 	}
> }
> catch {
> 	Write-Error -Message "Command failed." -Category "InvalidResult"
> }
> ```

I check your install.ps1, and obviously your test code block miss a param. In my point of view, the test code block should be like below, which is just like what you guys write in install.ps1.
```powershell
$env:CCLONE_ATTR = ''
$env:CCDEST_DIR ??= "$env:XDG_CONFIG_HOME\nvim"

try {
    Invoke-Command -ErrorAction Stop -ScriptBlock { git clone --progress -b main "$env:CCLONE_ATTR" 'https://github.com/ayamir/nvimdots.git' "$env:CCDEST_DIR"}
    if (-not $?) {
        throw
    }
}
catch {
    Write-Error -Message "Command failed." -Category "InvalidResult"
}
```
And in this case, run test.ps1 cause "fatal: Too many arguments.", which is just the same as what i got in my issue. Obviously the problem is that although $env:CCLONE_ATTR == "", "$env:CCLONE_ATTR" was wrongly treated as the first parameter. As a result, $env:CCLONE_ATTR = "" cause error and $env:CCLONE_ATTR = "--depth=1" is right. This problem is clear now.

**Comment by Jint-lzxy** [comment] 2023-04-21 08:35
> and obviously your test code block miss a param

It's okay as this issue is not related to those subsequent commands, cloning to the current working directory is sufficient tho.

> was wrongly treated as the first parameter.

Great 👍 Many thanks for helping us with the testing. This is consistent with the results on macOS.
Will use array expansion to pass in those parameters instead.

**Comment by FangLin2001** [comment] 2023-04-21 08:38
> It's okay as this issue is not related to those subsequent commands, cloning to the current working directory is sufficient tho.

Yes, that doesnt matter much, just error info differs: fatal: repository '' does not exist

**Comment by Jint-lzxy** [comment] 2023-04-21 08:39
> Yes, that doesnt matter much, just error info differs: fatal: repository '' does not exist

This is actually one thing, isn't it 😆

**Comment by Jint-lzxy** [comment] 2023-04-21 08:47
@FangLin2001 Quick fix: https://github.com/ayamir/nvimdots/commit/a26c878a046dedc3d69731aee86ffedbb997c705. You may need to wait for `raw.githubusercontent.com` to refresh.

**Comment by FangLin2001** [comment] 2023-04-21 08:53
> @FangLin2001 Quick fix: [a26c878](https://github.com/ayamir/nvimdots/commit/a26c878a046dedc3d69731aee86ffedbb997c705). You may need to wait for `raw.githubusercontent.com` to refresh.

I'm forced to use --depth=1 to finish my installation already. So it helps others who want to turn off shallow clone.

**Comment by Jint-lzxy** [comment] 2023-04-21 09:00
> I'm forced to use --depth=1 to finish my installation already.

If you still wish a complete clone, you can remove the old installation first:
```pwsh
Remove-Item -Recurse -Force "$env:LOCALAPPDATA\nvim"
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.ps1'))
```

But partial cloning would suffice for non-development purposes 😄

**Comment by CharlesChiuGit** [comment] 2023-04-21 09:12
The script still works for me. (duh

![圖片](https://user-images.githubusercontent.com/32497323/233596818-8a2e37ae-9ca4-407f-8a4b-8b82ca5bf1a1.png)

**Comment by Jint-lzxy** [comment] 2023-04-21 09:15
> Although I still encounter npm UNABLE_TO_VERIFY_LEAF_SIGNATURE error in NodeJS dependencies check

@FangLin2001 Can you try setting `$env:NODE_TLS_REJECT_UNAUTHORIZED = "0"` (or to `$False` if `"0"` isn't recognized) before executing `npm install --global neovim tree-sitter-cli`? Looks like your proxy failed to return a trustworthy certificate.
However, do note that this method is not secure and is only used to test if the issue is caused by your proxy. Please unset this variable after confirmation: `$env:NODE_TLS_REJECT_UNAUTHORIZED = ''`

**Comment by Jint-lzxy** [comment] 2023-04-21 09:38
> Hmm but I can't think of a reason why we should implement this - FWIW branch detection based on `nvim --version` would suffice.
> 
> In fact, if ppl really want to customize their clone branch, `CCLONE_BRANCH` is reserved as a global option for them 😄
> 
> https://github.com/ayamir/nvimdots/blob/f1c5f091c5f4fd8d41c92d29085f96984ba1aebb/scripts/install.ps1#L22

cc @CharlesChiuGit in case u missed that :)

**Comment by CharlesChiuGit** [comment] 2023-04-21 09:54
> > Hmm but I can't think of a reason why we should implement this - FWIW branch detection based on `nvim --version` would suffice.
> > In fact, if ppl really want to customize their clone branch, `CCLONE_BRANCH` is reserved as a global option for them 😄
> > https://github.com/ayamir/nvimdots/blob/f1c5f091c5f4fd8d41c92d29085f96984ba1aebb/scripts/install.ps1#L22

@Jint-lzxy lol I have transfer it to #675 , since I think it's better not to start two conversation in one thread.🤣

**Comment by FangLin2001** [comment] 2023-04-21 09:55
> @FangLin2001 Can you try setting `$env:NODE_TLS_REJECT_UNAUTHORIZED = 0` (or to `$False` if `0` isn't recognized) before executing `npm install --global neovim tree-sitter-cli`? Looks like your proxy failed to return a trustworthy certificate.

You are right as npm install succeed if disabling certificate verification.

**Comment by Jint-lzxy** [comment] 2023-04-21 10:00
> You are right as npm install succeed if disabling certificate verification.

I would suggest you contact ur proxy provider since we as users cannot do much to resolve this client-side issue.

***

Closing as all the mentioned issues have been resolved. If u have any other related questions, feel free to reopen this at any time!

**Closed by Jint-lzxy** 2023-04-21 10:00 UTC
Labels: bug, needs:response, has:repro, platform:windows
