### ISSUE TITLE
Passing custom arguments while debugging via dap

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#440] opened 2023-01-28 04:22 UTC
### Feature description

well，I find out that our dap configuration is lack of passing custom arguments ability  when I'm debugging some c++ programs that require the user to enter their own arguments. thus I wonder whether we should change the dap configuration to support custom arguments, or just let users do it themselves?

**Comment by Jint-lzxy** [comment] 2023-01-28 05:25
You mean to accept **command line arguments** or **`stdin`** _(user input)_?

Command line arguments can be passed in through `preRunCommands = {'settings set -- target.run-args  "<your>" "<args>"'}`, just add a query function to read and separate the arguments. If this is what you request, I will add this feature later. (After #394)

btw, as different debuggers have their own initialization methods, it is impossible to make a feature available on all debuggers at the same time. The best way is to read the documentation of a debugger and add the corresponding options in the configuration.

If you mean redirecting **user input**, the best way I can think of now is to redirect `stdin` to a file. I will look into this issue later.

**Comment by Jint-lzxy** [comment] 2023-01-28 05:28
(`preRunCommands = {'settings set -- target.input-path <file>'}`)

**Comment by csyJoy** [comment] 2023-01-28 05:52
> You mean to accept **command line arguments** or **`stdin`** _(user input)_?
> 
> Command line arguments can be passed in through `preRunCommands = {'settings set -- target.run-args "<your>" "<args>"'}`, just add a query function to read and separate the arguments. If this is what you request, I will add this feature later. (After #394)
> 
> btw, as different debuggers have their own initialization methods, it is impossible to make a feature available on all debuggers at the same time. The best way is to read the documentation of a debugger and add the corresponding options in the configuration.
> 
> If you mean redirecting **user input**, the best way I can think of now is to redirect `stdin` to a file. I will look into this issue later.

sorry for my vague expression, actually I mean *user input*, I've read the dap document and found the `arg` field can pass user inputs while launching dap, it works good for me. 

I think your comment to this issue is right, It's better to let users config themselves, should I close this issue?

**Comment by Jint-lzxy** [comment] 2023-01-28 06:05
> sorry for my vague expression, actually I mean _user input_, I've read the dap document and found the `arg` field can pass user inputs while launching dap, it works good for me.

hmm my interpretation of the issue is to allow users to input interactively during a debugging session.. But if this works for you, you may close this issue at any time 👍

**Comment by Jint-lzxy** [comment] 2023-01-28 11:35
IMO there are many options available, and we should leave the choices to users.

- Alternative 1: [lldb-vscode#attaching-settings](https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-vscode#attaching-settings)
- Alternative 2: [dap-terminal](https://github.com/mfussenegger/nvim-dap/blob/d213b7d5bf0d56b1f47c62a2f5d4ebd202fe0d12/doc/dap.txt#L540)
- Alternative 3: Redirect `stdin`

**Closed by Jint-lzxy** 2023-01-28 11:35 UTC
Labels: enhancement, complexity:low, dap
