### ISSUE TITLE
unexpected token `??=` in windows install script

### ISSUE THREAD

**Issue by cc020608** [ayamir/nvimdots#1021] opened 2023-10-15 06:37 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

win11

### Terminal name/version

termianl

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

当我以管理员身份打开终端后，执行Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.ps1'))这条指令就报错了。报错信息如下：
Invoke-Expression : 所在位置 行:21 字符: 22
+ $env:XDG_CONFIG_HOME ??= $env:LOCALAPPDATA
+                      ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:22 字符: 17
+ $env:CCPACK_MGR ??= 'unknown'
+                 ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:23 字符: 20
+ $env:CCLONE_BRANCH ??= 'main'
+                    ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:24 字符: 18
+ $env:CCLONE_ATTR ??= 'undef'
+                  ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:25 字符: 17
+ $env:CCDEST_DIR ??= "$env:XDG_CONFIG_HOME\nvim"
+                 ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:1 字符: 51
+ ... ess -Force; Invoke-Expression ((New-Object System.Net.WebClient).Down ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseExcep
   tion
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.In
   vokeExpressionCommand

### Expected behavior

请问如何解决

**Comment by CharlesChiuGit** [comment] 2023-10-15 06:56
what's your pwsh version?

**Comment by cc020608** [comment] 2023-10-15 07:01
> what's your pwsh version?

7.3.8

**Comment by Jint-lzxy** [comment] 2023-10-15 07:38
> 7.3.8

Possible duplicate of #636. Did u use the correct executable? ([null-coalescing assignment operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-7.3#null-coalescing-assignment-operator) was introduced in PowerShell 7.1.)

**Comment by cc020608** [comment] 2023-10-15 07:51
I dont understand what you mean

**Comment by Jint-lzxy** [comment] 2023-10-15 07:55
Check the output of `Get-Host`, does it tell u that u're using PowerShell 7.3.8?

**Comment by cc020608** [comment] 2023-10-15 09:54
Thank you very much, I opened the thick terminal.Now I have solved the problem.

**Closed** 2023-10-15 11:30 UTC
Labels: duplicate, question, platform:windows, env, invalid:misc
