### ISSUE TITLE
add scheme/theme support for gruvbox

### ISSUE THREAD

**Issue by shelper** [ayamir/nvimdots#435] opened 2023-01-24 21:48 UTC
### Feature description

could you add support for this scheme? https://github.com/ellisonleao/gruvbox.nvim

i searched yoru doc only found that i can only use limited sets of scheme
and no details on how i can install one to fit into your config.

**Comment by ayamir** [comment] 2023-01-25 02:18
refer to this: https://github.com/ayamir/nvimdots/issues/353

**Comment by Jint-lzxy** [comment] 2023-01-25 15:58
Closed as a duplicate of #353.

**Closed by Jint-lzxy** 2023-01-25 15:58 UTC
Labels: duplicate, usage
