### ISSUE TITLE
`toggleterm.nvim` behaves wierd in Alacritty

### ISSUE THREAD

**Issue by LYK-love** [ayamir/nvimdots#820] opened 2023-06-24 16:48 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macOS 13.2.1

### Terminal name/version

alacritty 0.12.1

### $TERM environment variable

xterm-256clolor

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

In alacritty:

1. Use nvim to open any file.
2. In normal mode, toggle one terminal. Use` <A-\>/<F5>` or `<C-\>`
3. The toggled terminal has wierd cursor. The cursor image is aways "block",  it's nearlt transparent and keeps blinking fast. User can hardly identifier the cursor. The cursor outside nvim is normal, but in toggled terminal in nvim, it's different from that.

I can't give a direct screenshot because the cursor blinks very fast and it's hard to see.
<img width="717" alt="image" src="https://github.com/ayamir/nvimdots/assets/74082944/ab591306-0fce-4320-89bc-5c07e366384d">

Then I changed the config of my alacritty(`alacritty.yml`). Change my cursor to `Underline`, not `Block`. 
<img width="892" alt="image" src="https://github.com/ayamir/nvimdots/assets/74082944/a6687943-899f-4af0-b514-7a6641daedf1">

1. In the terminal toggled by `Toggleterm` in nvim, the cursor is still the same.
2. Outside the nvim, the cursor of alacritty changes correctly( becomes "Uniderline", not "Block"):
<img width="554" alt="image" src="https://github.com/ayamir/nvimdots/assets/74082944/c04751cf-aed3-467a-a55c-0c16ad4449d2">

Then the wierdest thing happens:
1. I enter the nvim, toggle an terminal, the cursor in it becomes the weird version again("Block", blinking...). Then I exit the terminal, exit nvim, go back to my alacritty zsh environment. The cursor doesn't change, it's still block and blinking!
2. I exit alacritty and reopen it, the cursor becomes corrent.

I've tried many times for above procedures.
To fix it, I've reinstalled atamir's nvim, reintall nvim, deleted `~/.local/share/nvim` and reintalled alacritty. The problem's still there.
I do the same operations in my iTerm2(Build 3.5.0beta4) and WezTerm(Version20230408), the `toggleterm` plugin works fine in it. It seems that  the problem only lies in alacritty.

### Expected behavior

The cursor in terminal should be normal. And it should also can change according to the config file.

**Comment by ayamir** [comment] 2023-06-25 02:37
> I do the same operations in my iTerm2(Build 3.5.0beta4) and WezTerm(Version20230408), the toggleterm plugin works fine in it. It seems that the problem only lies in alacritty.

So this has nothing to do with our config, just `alacritty` has this problem, right?

**Comment by LYK-love** [comment] 2023-06-25 10:50
> > I do the same operations in my iTerm2(Build 3.5.0beta4) and WezTerm(Version20230408), the toggleterm plugin works fine in it. It seems that the problem only lies in alacritty.
> 
> So it has nothing to do with our config, just `alacritty` has this problem, right?

Emmm I don't know. Both `toggleterm.nvim` and alacritty are possible to have problem. I want to know if anyone else using alacritty encounter this.

**Comment by ayamir** [comment] 2023-06-26 03:16
Can't repro on my gentoo linux with alacritty 0.12.0.
![screensht_23-06-26_11:15:50](https://github.com/ayamir/nvimdots/assets/61657399/f8157d77-5703-4c6d-8aa2-b3c757581283)

**Comment by ayamir** [comment] 2023-07-02 02:59
Any progress?

**Comment by LYK-love** [comment] 2023-07-02 07:16
> Any progress?

No... I hope someone wih the same environment ( alacritty, macos, nvim, ayamir's nvim config )can reproduce it.

**Comment by ayamir** [comment] 2023-07-02 08:40
Maybe have to do with the shell prompt?

**Comment by LYK-love** [comment] 2023-07-02 13:20
> Maybe have to do with the shell prompt?

No, it's about the cursor.

**Comment by Jint-lzxy** [comment] 2023-07-02 17:08
Hmmm but I also can't repro this with a freshly installed [Alacritty-v0.12.2](https://github.com/alacritty/alacritty/releases/download/v0.12.2/Alacritty-v0.12.2.dmg) via Homebrew Casks _(I don't use Alacritty, so everything should be the default)_, an Intel mac with macOS 13.4.1 in operation and Neovim v0.9.1 (zsh) 😢 Try debugging your config to see if there's any issue with that?

<img width="450" alt="sysinf" src="https://github.com/ayamir/nvimdots/assets/50296129/c650b6ed-760b-4406-a72f-0b02673036e7">

**Comment by ayamir** [comment] 2023-07-14 13:02
I will close it due to lacking reproducibility, feel free to reopen it if any other reproduce this issue.

**Closed by ayamir** 2023-07-14 13:02 UTC
Labels: bug, needs:repro, env
