### ISSUE TITLE
The mapping does not work as designed in debug mode

### ISSUE THREAD

**Issue by YuCao16** [ayamir/nvimdots#899] opened 2023-07-27 12:57 UTC
### Version confirmation

- [x] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-618+g4fd852b8c

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Go to Debug mode
2. Press K in code buffer

### Expected behavior

K is bound to `lua require("dapui").eval()`

### Actual behavior

K is bound to `Lspsaga hover_doc'

### Additional information

In the most recent version, 'K' has been bound to lua require("dapui").eval(). However, in the main code window, this mapping has not been overwritten. There are two reasons for this:

1. Some LSP clients, such as copilot, are attached after entering debug mode.
2. LSP-related mappings are not overwritten. I need to specify the 'bufnr' for it to work.
 ```
	["n|K"] = map_cmd("<Cmd>lua require('dapui').eval()<CR>")
		:with_buffer(0)
		:with_noremap()
		:with_nowait()
		:with_desc("debug: Evaluate expression under cursor"),
```
I'm not sure if this is a real issue or a conflict between my own configuration and the current version. Could you please test it?

**Comment by Jint-lzxy** [comment] 2023-07-27 13:25
Cannot repro. We did test this before merging #877.

This is a global keymap, so it's impossible for a _specific_ buffer to have a different definition (unless overridden). And theoretically no LSP activity is allowed during this period. Can you provide a minimum repro so that we can look into this issue?

**Comment by YuCao16** [comment] 2023-07-27 15:36
> How about `K` in `visual mode`? does that works?

Yes, it works as expect in visual mode.

**Comment by YuCao16** [comment] 2023-07-27 16:06
> 

I'm not sure if this issue is caused by the problem of having multiple LSPs attached or something similar, since specifying the bufnr (:with_buffer(0)) seems to resolve it. In addition, the restoration method may not be comprehensive. The original K mapping is linked to those buffers with LSPs attached, but the restoration method does not specify this.

**Comment by Jint-lzxy** [comment] 2023-07-27 16:10
> can u confirm this part?

Yeah I encountered this issue log ago, but forgot to port it upstream 🤦‍♂️ Thanks for the heads up! To be short, if the config (for `lua_ls`) is set in lspconfig, the surprising thing is, two `lua_ls`s will be spawned (to identify this, sending `lsp_hover` will generate duplicate results), one is for that without config, and the other is with config. The solution is to set up `lua_ls` on a per-project basis. See: [Jint-lzxy/nvimconfig/.luarc.json](https://github.com/Jint-lzxy/nvimconfig/blob/master/.luarc.json)

**Comment by Jint-lzxy** [comment] 2023-07-27 16:12
@YuCao16 Can u provide a minimum repro? I have the correct setup prepared, but somehow cannot reproduce this 😢

**Comment by Jint-lzxy** [comment] 2023-07-27 16:23
![demo](https://github.com/ayamir/nvimdots/assets/50296129/12251f92-33ea-40ef-b5d4-0ce7cf6da18b)

**Comment by CharlesChiuGit** [comment] 2023-07-27 16:29
Just guessing.

`with_buffer()` will make the keymap have higher priority over other non-`with_buffer()` keymap.

So the loading order might be:

1. First `LspAttach` -> bind `n|K]` to `Lspsaga hover_doc`
2. DAP got loaded -> bind `[n|K]` to `lua require("dapui").eval()` But since it don't have `with_buffer()` priority, so it can't overwrite LSP keymap.

If u give DAP keymap `with_buffer()` priority, then `[n|K]` will be decided by the loading order.
https://neovim.io/doc/user/api.html#nvim_buf_set_keymap()

**Comment by YuCao16** [comment] 2023-07-27 16:30
I try to create a easier way to reproduce this issue, could you please try this?
1. add this line: `["n|<leader>pz"] = map_cr("Lazy"):with_buffer(0):with_silent():with_noremap():with_nowait():with_desc("package: Clean"),
` into `nvim/lua/keymap/init.lua`
2. add this line `["n|<leader>pz"] = map_cmd("<Cmd>lua require('dapui').eval()<CR>"):with_silent():with_noremap():with_nowait():with_desc("package: Clean"),
` into `nvim/lua/modules/configs/tool/dap/dap-keymap.lua` line 14.

So the `<leader>pz` should be bound to `lau require('dapui').eval()` in debug mode, but in my side, it still be bound to `Lazy`. And in other buffer such as `dapui_scopes`, it has been bound to `lua require('dapui').eval()` correctly.

**Comment by YuCao16** [comment] 2023-07-27 16:31
> Just guessing.
> 
> `with_buffer()` will make the keymap have higher priority over other non-`with_buffer()` keymap.
> 
> So the loading order might be:
> 
>     1. First `LspAttach` -> bind `n|K]` to `Lspsaga hover_doc`
> 
>     2. DAP got loaded -> bind `[n|K]` to `lua require("dapui").eval()` But since it don't have `with_buffer()` priority, so it can't overwrite LSP keymap.
> 
> 
> If u give DAP keymap `with_buffer()` priority, then `[n|K]` will be decided by the loading order.
> 
> https://neovim.io/doc/user/api.html#nvim_buf_set_keymap() I think buffer-local keymap will have higher priority then global keymap?

I think so ...

**Comment by YuCao16** [comment] 2023-07-27 16:38
Shall we just use another mechanism to setup key mapping, for example, based on filetype? I can send a pr if you accept.

**Comment by Jint-lzxy** [comment] 2023-07-27 16:38
> but if so, why can't you reproduce it?

Yeah it's quite strange... I can reproduce https://github.com/ayamir/nvimdots/issues/899#issuecomment-1653959926 but the same thing doesn't apply to this issue. I'm checking the log to see if there's anything useful.

**Comment by Jint-lzxy** [comment] 2023-07-27 16:42
> Shall we just use another mechanism to setup key mapping, for example, based on filetype? I can send a pr if you accept.

But FWIW this keymap should be globally available in the current debug session, as the debugger could potentially switch files, and once the buffer changed, those keymaps will be invalidated.

**Comment by Jint-lzxy** [comment] 2023-07-27 16:54
Oh I see where the issue is. I'm using Neovim v0.9.1 on this host, but once I switch to Neovim nighly, the problem appears:
```console
執行 LspAttaach Autocommands: "*"
autocommand <*>
autocommand <*>
...
執行 LspAttaach Autocommands: "*"
autocommand <*>
...
執行 LspAttaach Autocommands: "*"
autocommand <*>
...
執行 LspAttaach Autocommands: "*"
autocommand <*>
...
執行 LspAttaach Autocommands: "*"
autocommand <*>
......
```
Not sure why this event got triggered when no (new) LSP attached to that buffer...

**Comment by YuCao16** [comment] 2023-07-27 16:56
> > Shall we just use another mechanism to setup key mapping, for example, based on filetype? I can send a pr if you accept.
> 
> But FWIW this keymap should be globally available in the current debug session, as the debugger could potentially switch files, and once the buffer changed, those keymaps will be invalidated.

What if we set keymap based on filetype, for example `python` and `dapui_*`, this will simply the restore function.

**Comment by YuCao16** [comment] 2023-07-27 16:58
> Oh I see where the issue is. I'm using Neovim v0.9.1 on this host, but once I switch to Neovim nighly, the problem appears:
> 
> ```
> 執行 LspAttach Autocommands: "*"
> autocommand <*>
> autocommand <*>
> ...
> 執行 LspAttach Autocommands: "*"
> autocommand <*>
> ...
> 執行 LspAttach Autocommands: "*"
> autocommand <*>
> ...
> 執行 LspAttach Autocommands: "*"
> autocommand <*>
> ...
> 執行 LspAttach Autocommands: "*"
> autocommand <*>
> ......
> ```
> 
> Not sure why this event got triggered when no (new) LSP attached to that buffer...

V0.10.0-dev is the most bug-ridden version I've ever encountered. Almost every day I'm facing bugs that emerge from who knows where.

**Comment by Jint-lzxy** [comment] 2023-07-27 17:03
> What if we set keymap based on filetype, for example `python` and `dapui_*`, and use callable, define a function to `pcall` `require('dapui').eval()`? this will simply the restore function.

That thought crossed my mind as well. But the issue is, some languages may have multiple filetypes that meet the criteria (e.g., `.c[pp]` (c/cpp) and `.h` (header)). I don't think we can exhaust all those combinations, not to mention user ftplugins and bigfile.nvim.

**Comment by YuCao16** [comment] 2023-07-27 17:06
> > What if we set keymap based on filetype, for example `python` and `dapui_*`, and use callable, define a function to `pcall` `require('dapui').eval()`? this will simply the restore function.
> 
> That thought crossed my mind as well. But the issue is, some languages may have multiple filetypes that meet the criteria (e.g., `.c[pp]` (c/cpp) and `.h` (header)). I don't think we can exhaust all those combinations, not to mention user ftplugins and bigfile.nvim.

Is `require('dapui').eval()` works in `*.h`?

**Comment by Jint-lzxy** [comment] 2023-07-27 17:07
> V0.10.0-dev is the most bug-ridden version I've ever encountered. Almost every day I'm facing bugs that emerge from who knows where.

TBH nightly builds have always been like this. We never know what the next "surprise" is :D

**Comment by Jint-lzxy** [comment] 2023-07-27 17:15
IMO the most effective (and "economical") way is to revert #735, but is it worth it?

**Comment by YuCao16** [comment] 2023-07-27 17:22
> IMO the most effective (and "economical") way is to revert #735, but is it worth it?

Just bind `K` to a callable function should works, we should only detect if we are in debug mode or not.

**Comment by Jint-lzxy** [comment] 2023-07-27 17:32
> Just bind `K` to a callable function should works, we should only detect if we are in debug mode or not.

In fact, this was my initial proposal (`_G._debugging`) but [I reverted that](https://github.com/ayamir/nvimdots/pull/877/commits/c6c7af58c7127065764481a273ef5f390593ff95) b/c I didn't feel like introducing global variables was a good choice - that will make the base config more difficult to understand. But considering the current situation, if it takes tooooooo long for Neovim core to identify/fix this issue, this sounds appealing to me! I'll open a PR for this 😄

**Comment by YuCao16** [comment] 2023-07-27 17:39
> > Just bind `K` to a callable function should works, we should only detect if we are in debug mode or not.
> 
> In fact, this was my initial proposal (`_G._debugging`) but [I reverted that](https://github.com/ayamir/nvimdots/pull/877/commits/c6c7af58c7127065764481a273ef5f390593ff95) b/c I didn't feel like introducing global variables was a good choice - that will make the base config more difficult to understand. But considering the current situation, if it takes tooooooo long for Neovim core to identify/fix this issue, this sounds appealing to me! I'll open a PR for this smile

Maybe detect if buffer with filetype `dapui_scopes` exist will prevent create a global variable?

**Comment by Jint-lzxy** [comment] 2023-07-27 17:44
> Maybe detect if buffer with filetype `dapui_scopes` exist will prevent create a global variable?

Sorry I didn't get this, what's the point of detecting buffers with filetype `dapui_scopes`?

**Comment by YuCao16** [comment] 2023-07-27 17:46
> > Maybe detect if buffer with filetype `dapui_scopes` exist will prevent create a global variable?
> 
> Sorry I didn't get this, what's the point of detecting buffers with filetype `dapui_scopes`?

I mean we can detect if there is a dapui's window so we know if we are in debug mode, dapui_scopes is one of them.

**Comment by Jint-lzxy** [comment] 2023-07-27 17:47
I would prefer setting this up by registering callbacks during `dap_initialized` (post) and `dap_terminated` (pre) :) This would be a more generic way to achieve that.

**Comment by YuCao16** [comment] 2023-07-27 17:48
> I would prefer setting this up by registering callbacks during `dap_initialized` (post) and `dap_terminated` (pre) :) This would be a more generic way to achieve that.

Agreed, that's more decent, thanks for your effort.

**Comment by YuCao16** [comment] 2023-07-28 10:31
@Jint-lzxy This seems happen again after merging the latest commit...

**Comment by Jint-lzxy** [comment] 2023-07-28 10:40
@YuCao16 Ah yes many thanks for reminding me. This is now a specific issue for Neovim nightly, as these keymaps are set by repeated `LspAttach` event even after they get cleared. lemme me think a bit about how to fix this.

**Comment by Jint-lzxy** [comment] 2023-07-28 11:24
@YuCao16 Does https://github.com/ayamir/nvimdots/pull/907 fix this?

**Comment by YuCao16** [comment] 2023-07-28 11:27
> @YuCao16 Does #907 fix this?

This, it works!

**Closed** 2023-07-28 15:19 UTC
Labels: bug, has:repro, keymap, dap, nvim:nightly
