### ISSUE TITLE
lualine 提示 invalid key

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#408] opened 2023-01-06 02:22 UTC
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

Windows 10

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

更换lualine主题

### Expected behavior

不报错

### Actual behavior

更换lualine的主题后（ui/config 249 line）

打开文件提示如下：
packer.nvim: Error running config for lualine.nvim: ......utils/init.lua:62 invalid key

如果把ui/config的 302--307注释掉，就不会报错了
![2023-01-06 10_21_36-Window](https://user-images.githubusercontent.com/13484700/210916877-7c399e55-5ff6-4c74-8eb9-73bdcae7c8f1.png)

**Comment by CharlesChiuGit** [comment] 2023-01-06 02:26
This is probably depends on your colorscheme which doesn't have this highlight group. So u can do 2 things to solve it:
1. use this repo's colorscheme
2. define the highlight group yourself.

**Comment by Jint-lzxy** [comment] 2023-01-06 03:28
This should be fixed by #405. Which theme did you switch to for lualine?

**Comment by nkta3m** [comment] 2023-01-06 03:59
i set lualine theme to carbonfox

**Comment by Jint-lzxy** [comment] 2023-01-06 04:15
<img width="966" alt="lualine-warning" src="https://user-images.githubusercontent.com/50296129/210928392-2e6fe530-390b-4e1a-a8cc-ec588df28059.png">

Is this the theme of another colorscheme? Loos like `lualine` does not have this scheme built in. I tried to search on Google and got `EdenEast/lightfox.nvim`.

**Comment by nkta3m** [comment] 2023-01-06 04:18
carbonfox is part of https://github.com/EdenEast/nightfox.nvim

**Comment by Jint-lzxy** [comment] 2023-01-06 04:27
Can reproduce. Looks like there's a problem working with linked highlight groups. I will rewrite this function _(for merging highlight groups)_ later. Now you can comment out these lines as a temporary workaround 👍

**Comment by nkta3m** [comment] 2023-01-06 04:35
ok

**Comment by Jint-lzxy** [comment] 2023-01-06 08:21
@nkta3m #409 should be able to address this problem. You can test whether this issue is resolved after the PR is merged.

**Comment by nkta3m** [comment] 2023-01-06 09:09
解决了，效果如下：
![2023-01-06 17_07_50-Window](https://user-images.githubusercontent.com/13484700/210968719-1a206a19-8b18-4189-941d-72abcd9f68cf.png)

非常感谢！

**Comment by Jint-lzxy** [comment] 2023-01-06 12:49
@nkta3m This PR has not been merged yet. If you want to test it now, you can clone my branch:
- **ssh:** `git clone git@github.com:Jint-lzxy/nvimdots.git && cd nvimdots && git checkout utils-fix`
- **https:** `git clone https://github.com/Jint-lzxy/nvimdots.git && cd nvimdots && git checkout utils-fix`
- **github CLI:** `gh pr checkout 409`

**Comment by ayamir** [comment] 2023-01-06 14:14
> @nkta3m This PR has not been merged yet. If you want to test it now, you can clone my branch:
> 
> * **ssh:** `git clone git@github.com:Jint-lzxy/nvimdots.git && cd nvimdots && git checkout utils-fix`
> * **https:** `git clone https://github.com/Jint-lzxy/nvimdots.git && cd nvimdots && git checkout utils-fix`
> * **github CLI:** `gh pr checkout 409`
> 
> <img alt="demo" width="1786" src="https://user-images.githubusercontent.com/50296129/211017823-9cc8e49d-2d19-4ff6-8260-7942c9f67fac.png">
> 
> I did some tests, and there were no errors when using the default `nightfox` colorscheme

In other way, no need to clone, just add you repo as a remote origin.
```
git remote add jint git@github.com:Jint-lzxy/nvimdots.git
git fetch jint
git checkout utils-fix
```

**Comment by nkta3m** [comment] 2023-01-07 01:46
我测试也OK了，没有报错了，👍

**Closed** 2023-01-07 01:59 UTC
Labels: bug, has:workaround, has:repro
