### ISSUE TITLE
Alt key for mac

### ISSUE THREAD

**Issue by dadanliu** [ayamir/nvimdots#549] opened 2023-03-05 02:08 UTC
### Feature description

\<A-d\> 中的 A。对的mac里的按键是什么，options么？按了半天没找到...

**Comment by ClSlaid** [comment] 2023-03-05 04:14
非 Macbook 用户，美式键盘应当是 `Options` 键。建议上网搜索。

**Comment by ayamir** [comment] 2023-03-05 09:25
What's your terminal?

**Comment by dadanliu** [comment] 2023-03-05 11:01
> 

iterm2 and option just not work;

**Comment by Jint-lzxy** [comment] 2023-03-05 11:23
Duplicate of #344. Please search existing issues before opening a new one.

**Closed** 2023-03-05 11:23 UTC
Labels: duplicate, keymap, platform:macos
