### ISSUE TITLE
New icons in completion panel

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#626] opened 2023-04-08 01:37 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open any file
2. In INSERT mode press `d`, `e` or some other keys

### Expected behavior

Icons in completion panel render normally

### Actual behavior

![image](https://user-images.githubusercontent.com/73375859/230697647-9d51690e-9608-48d2-a294-847f91daa976.png)

![image](https://user-images.githubusercontent.com/73375859/230697749-17f1a906-f29b-4816-a6aa-e02616821a4e.png)

### Additional information

Probably it's caused LSP update?

**Comment by Jint-lzxy** [comment] 2023-04-08 05:08
Duplicate of #624. This is part of the v0.9 migration.

**Closed by Jint-lzxy** 2023-04-08 05:08 UTC
Labels: bug
