### ISSUE TITLE
use native lsp inline virtual text on neovim nightly

### ISSUE THREAD

**Issue by ClSlaid** [ayamir/nvimdots#815] opened 2023-06-22 14:29 UTC
### Feature description

NeoVim nightly just got native inlay virtual text support. `0.10` branch now could get rid of `lsp-inlayhints.nvim`.

![图片](https://github.com/ayamir/nvimdots/assets/44747719/63616460-c80a-4599-b4ea-5bbbe3b390a5)

showcase with rust
![图片](https://github.com/ayamir/nvimdots/assets/44747719/8ad14241-8211-4172-be5c-2406acb05dbb)

**Comment by CharlesChiuGit** [comment] 2023-06-22 16:11
Up vote for removing `lsp-inlayhints.nvim` and `lsp_signature` in 0.10 branch. (Personally I don't use lsp signature's functionality)
I'm not sure about `pylyzer` tho, never tried it before.

**Comment by ayamir** [comment] 2023-06-22 16:21
> Can we also get rid of lsp_signature, it's the reason of many delay of nvim-cmp. However most python lsp (I primarily use python) doesn't support inlay hint, maybe change to [pylyzer](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#pylyzer)?

IMO inlay hint isn't so important to make us replace `pylsp` with `pylyzer` which isn't tried and tested very well.

**Comment by Jint-lzxy** [comment] 2023-06-23 04:05
> Can we also get rid of lsp_signature, it's the reason of many delay of nvim-cmp.

IMHO We should keep lsp_signature b/c we need this for languages that require information related to function signatures (e.g., languages that support function overloading like C++). This delay is actually [an upstream issue](https://github.com/hrsh7th/nvim-cmp/issues/1613).

> However, is there any way to test the differences between LSPs to check if Pylyzer is better (or worse)?

Check if it supports maximum [server capabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize) (subsection `TextDocumentClientCapabilities`).

**Comment by volpan** [comment] 2023-07-06 11:42
Maybe have a look at [this](https://github.com/volpan/nvim/commit/c64ef6c478fb5b87007f68ac8f87b8337ccac814) as a ref.

**Comment by CharlesChiuGit** [comment] 2023-07-07 08:29
> Maybe have a look at [this](https://github.com/volpan/nvim/commit/c64ef6c478fb5b87007f68ac8f87b8337ccac814) as a ref.

I think it's not a bad idea to remove `lsp_signature` if u got time; however, then we will need to config each language servers, which would be quite a hustle for neovim new comers to config their own language servers.

To avoid issue overflow, I think it's keep the nvim config more on the sensible side.

**Comment by CharlesChiuGit** [comment] 2023-07-17 08:55
This feature is already implement in https://github.com/ayamir/nvimdots/tree/0.10 branch, closing this issue if no further discussion.

**Comment by fecet** [comment] 2023-07-17 13:03
> This feature is already implement in https://github.com/ayamir/nvimdots/tree/0.10 branch

This is implement by https://github.com/lvimuser/lsp-inlayhints.nvim, is there any reasonn to use it over native inlay support?

**Comment by CharlesChiuGit** [comment] 2023-07-18 01:59
> This is implement by [lvimuser/lsp-inlayhints.nvim](https://github.com/lvimuser/lsp-inlayhints.nvim), is there any reasonn to use it over native inlay support?

Sorry, miss that. reopen the issue.

**Comment by jczhang02** [comment] 2024-02-05 01:33
`pylance`  is a choice? I have found some open source implementations.

**Comment by CharlesChiuGit** [comment] 2024-02-05 02:10
> `pylance` is a choice? I have found some open source implementations.

I thought it wasn't legal to use `pylance` outside of vscode?

**Comment by fecet** [comment] 2024-02-05 03:34
https://github.com/mason-org/mason-registry/commit/a25ffdb8d0fd8e00f5f8c99e8f005b6c62cc6fd9

**Comment by jczhang02** [comment] 2024-02-05 03:53
> > `pylance` is a choice? I have found some open source implementations.
> 
> I thought it wasn't legal to use `pylance` outside of vscode?

Not legal, but  can be a choice.

**Comment by jczhang02** [comment] 2024-02-05 04:02
Perhaps we can recommend the development of the 0.10.0 branch. I would like to know who is willing to use version 0.10.0?

**Comment by CharlesChiuGit** [comment] 2024-02-05 04:06
hmmm, i not sure about this...
@Jint-lzxy @ayamir 
how to u think?

**Comment by CharlesChiuGit** [comment] 2024-02-05 04:09
> [mason-org/mason-registry@a25ffdb](https://github.com/mason-org/mason-registry/commit/a25ffdb8d0fd8e00f5f8c99e8f005b6c62cc6fd9)

it is being merged yet?

**Comment by ayamir** [comment] 2024-02-05 07:47
have not seen `pylance` in https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md.

**Comment by ayamir** [comment] 2024-02-09 08:22
2dfc8eafb1c52fcdf8f51c95751d5b2080ff4351

**Comment by Jint-lzxy** [comment] 2024-02-10 16:40
> how do u think?

Sorry I've been hit w/ a flu recently and might need to rest for a few more days 😢 But I'm w/ @ayamir on this, we could open a new issue for discussion. AFAIK even tho some LSs designed for vscode do offer some exclusive handy features, they usually come w/ licenses that strictly limit usage outside of vscode. IANAL but I've seen some issues caused by these licenses. The license is roughly phrased as follows:
```
You may use the software solely with
< list of VS products >
And you may not share, or publish the software to a third party without prior consent…
```
***
btw, happy lunar new year! 🎆 (finally made it home lol)

**Comment by CharlesChiuGit** [comment] 2024-02-11 00:55
@Jint-lzxy sad to hear that, hope u get well soon!

happy lunar new year to everyone too! 🎊

**Comment by ayamir** [comment] 2024-02-11 02:29
@Jint-lzxy Wishing you a speedy recovery and good health! And happy lunar new year! 🎉

**Closed by ayamir** 2024-02-11 02:29 UTC
Labels: enhancement, lsp

**Comment by vollowx** [comment] 2024-02-11 08:40
Happy new lunar year 🎉
