### ISSUE TITLE
Command suggestion not work properly: No candidates found

### ISSUE THREAD

**Issue by Tgist1024** [ayamir/nvimdots#521] opened 2023-02-15 01:52 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui

### Operating system/version

Arch linux 6.1.11

### Terminal name/version

kitty 0.27.1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open nvim.
2. Tab `:` to input commands.
3. Try to input something.

### Expected behavior

It should work fine.

### Actual behavior

No matter what input or not, the suggestion panel just displays `No candidates found`, and tab completion also doesn't work. If I tried to tab, my input became a single `0`.

#### No command input:
![image](https://user-images.githubusercontent.com/101801875/218906072-042a2c37-6227-4c17-81b1-509c90420a29.png)
#### Input command like `help`:
![image](https://user-images.githubusercontent.com/101801875/218906356-4bc9ab49-4650-425a-8186-e5e77f91912d.png)
#### Before using `tab` to complete commands:
![image](https://user-images.githubusercontent.com/101801875/218906575-688a12d9-d1bd-4a73-878b-4b733dc92633.png)
#### After:
![image](https://user-images.githubusercontent.com/101801875/218906649-bb9706e7-5d5d-4cee-a635-496b95a12fab.png)

`checkhealth` shows nothing wrong at all

**Comment by ayamir** [comment] 2023-02-15 02:35
Can't repo, but you can try `:UpdataRemotePlugins`

**Comment by Tgist1024** [comment] 2023-02-15 04:57
Tried, but still did not work.

**Comment by Tgist1024** [comment] 2023-02-15 04:58
Tried, but still did not work.

**Comment by nkta3m** [comment] 2023-02-15 05:36
I have same error

**Comment by nkta3m** [comment] 2023-02-15 05:54
check :messages
nvim-data/site/lazy/wilder.nvim/lua/wilder/internal.lua:4: loop or previous error loading module 'fzy-lua-native'

**Comment by Tgist1024** [comment] 2023-02-15 06:07
Got it, thanks. My error messages have a little different:
```
..share/nvim/site/lazy/wilder.nvim/lua/wilder/internal.lua:4: in function <...share/nvim/site/lazy/wilder.nvim/lua/wilder/internal.lua:3> function: builtin#18 ...share/n
vim/site/lazy/wilder.nvim/lua/wilder/internal.lua:4: attempt to index a boolean value
```
It seems to be an upstream error but found no similar issue in wilder.nvim, and that plugin looks like stop developing now.

**Comment by ayamir** [comment] 2023-02-15 07:34
Sorry, I can't reproduce it on my machine. I don't know any better solution than `rm -fr ~/.local/share/nvim/site/lazy/wilder.nvim` and then `nvim`.

**Comment by aarnphm** [comment] 2023-02-15 08:06
try 
```lua
runtime! vim/rtp.vim

UpdateRemotePlugins
```

**Comment by Tgist1024** [comment] 2023-02-15 08:44
Thanks for all your advice!
I decide to take a while to find an alternative to `wilder.nvim` because this seems just individual circumstances.

**Comment by aarnphm** [comment] 2023-02-15 09:08
I ran intot this issue b4. Maybe it has something to do with using `fzf-native-lua`. I notice that when I remove the pipeline setup, the error went away.

**Comment by HATTER-LONG** [comment] 2023-02-15 09:55
@Tgist1024 I got similar warning, I remove all plugin(` rm -rf ~/.local/share/nvim/* `) and reload again.
The problem disappears. I think you can try it.

**Comment by Yan-weihao** [comment] 2023-02-15 10:05
I also had the same problem, and when I started nvim, I also reported that I could not find the configuration file of the relevant plug-in

**Comment by Tgist1024** [comment] 2023-02-15 10:08
> @Tgist1024 I got similar warning, I remove all plugin(`rm -rf ~/.local/share/nvim/*`) and reload again. The problem disappears. I think you can try it.

Actually, I have tried this many times before.

**Comment by Tgist1024** [comment] 2023-02-15 10:11
> I ran intot this issue b4. Maybe it has something to do with using `fzf-native-lua`. I notice that when I remove the pipeline setup, the error went away.

It just works! Thank you!

**Comment by Jint-lzxy** [comment] 2023-02-15 14:28
@nkta3m @HATTER-LONG @Tgist1024 @Yan-weihao This _should_ be an upstream issue. Current workaround is to change `return require('.init')` in `~/.local/share/nvim/site/lazy/fzy-lua-native/lua/fzy-lua-native.lua` to `return require('init')`.

Looks like this is an issue related to native `rtp`. Maybe someone will be interested in looking into this weird behavior?

**Comment by Yan-weihao** [comment] 2023-02-15 18:56
> This _should_ be an upstream issue. Current workaround is to change `return require('.init')` in `~/.local/share/nvim/site/lazy/fzy-lua-native/lua/fzy-lua-native.lua` to `return require('init')` _(remove that period `.`)_.
> 
> Looks like this is an issue related to native `rtp`. Maybe someone will be interested in looking into this weird behavior?
> 
> cc @nkta3m @HATTER-LONG @Tgist1024 @Yan-weihao @aarnphm
![Screenshot_2023-02-16-02-55-12_1920x1080](https://user-images.githubusercontent.com/61379647/219125667-73b17b15-96f8-4829-a3ff-7347c18e82b9.png)
I am surprised that there is nothing in this file of mine

**Comment by Yan-weihao** [comment] 2023-02-15 19:01
> This _should_ be an upstream issue. Current workaround is to change `return require('.init')` in `~/.local/share/nvim/site/lazy/fzy-lua-native/lua/fzy-lua-native.lua` to `return require('init')` _(remove that period `.`)_.这应该是一个上游问题。当前的解决方法是将 `~/.local/share/nvim/site/lazy/fzy-lua-native/lua/fzy-lua-native.lua` 中的 `return require('.init')` 更改为 `return require('init')` （删除句点 `return require('.init')`）。
> 
> Looks like this is an issue related to native `rtp`. Maybe someone will be interested in looking into this weird behavior?看起来这是与原生 `rtp` 相关的问题。也许有人会对调查这种奇怪的行为感兴趣？
> 
> cc @nkta3m @HATTER-LONG @Tgist1024 @Yan-weihao @aarnphm

I re-installed this plug-in, and now it has worked, thanks for your reminding,
![Screenshot_2023-02-16-03-00-25_1920x1080](https://user-images.githubusercontent.com/61379647/219126923-e80b168f-6227-4a0d-a163-916a236af69d.png)

**Comment by CharlesChiuGit** [comment] 2023-02-16 06:52
I got the same issue after update `lazy.nvim`.

> Looks like this is an issue related to native `rtp`. Maybe someone will be interested in looking into this weird behavior?

I think the reason is that lazy clear the `rtp` for faster startup hence causing the issue.

**Comment by CharlesChiuGit** [comment] 2023-02-16 06:56
I have create a tmp fork and submit a PR to `fzy-lua-native`.

Others can use this tmp fork for now if u don't want to edit the file.
https://github.com/CharlesChiuGit/fzy-lua-native

**Comment by CharlesChiuGit** [comment] 2023-02-16 13:23
this version of nvim might fiz this issue.
![image](https://user-images.githubusercontent.com/32497323/219376402-9b628157-d115-4acc-85d2-d8b6248c7981.png)

**Closed** 2023-02-16 17:11 UTC
Labels: bug, help wanted, has:workaround, upstream
