### ISSUE TITLE
install fail : lazy async

### ISSUE THREAD

**Issue by Superman-wc** [ayamir/nvimdots#472] opened 2023-02-05 00:10 UTC
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.0-dev+374-ge13dcdf16

### Operating system/version

macOS 13.0 (22A380)

### Terminal name/version

iTerm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

处理 /Users/x/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: /Users/x/.config/nvim/lua/core/lazy.lua:130: module 'lazy' not found
:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/lazy.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/x/.config/nvim/lua/core/lazy.lua:130: in function 'load_lazy'
        /Users/x/.config/nvim/lua/core/lazy.lua:133: in main chunk
        [C]: in function 'require'
        /Users/x/.config/nvim/lua/core/init.lua:128: in function 'load_core'
        /Users/x/.config/nvim/lua/core/init.lua:136: in main chunk
        [C]: in function 'require'
        /Users/x/.config/nvim/init.lua:2: in main chunk

### Expected behavior

找不到模块lazy 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/11311755/216794893-6029a665-308d-4e2f-9796-ac2078b5af81.png">

**Comment by Jint-lzxy** [comment] 2023-02-05 01:56
Duplicate of https://github.com/ayamir/nvimdots/issues/445. Please run the following command:
```sh
rm -rf ~/.local/share/nvim/site/lazy
nvim
```

Also please ensure that `~/.local/share/nvim/site` only contains two folders: `lazy` and `lua`.

If you still experience this issue, please take a screenshot of the `!git clone` status during bootstrap.

***
A quick note here, the `0.8-dev` build is outdated. Please install a stable version instead.
If you use Homebrew:
```sh
brew update && brew upgrade && brew cleanup
brew uninstall nvim && brew install nvim
```

**Comment by Superman-wc** [comment] 2023-02-05 03:56
:!git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git /Users/superman/.local/share/nvim/site/lazy/l
azy.nvim
Cloning into '/Users/superman/.local/share/nvim/site/lazy/lazy.nvim'...
Note: switching to '9b208696e139a404d159963b975a5b90af38439b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

fatal: unable to access 'https://github.com/folke/lazy.nvim.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Oper
ation timed out, errno 60

**Comment by Jint-lzxy** [comment] 2023-02-05 04:19
> fatal: unable to access 'https://github.com/folke/lazy.nvim.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095): **Operation timed out, errno 60**

You can't access GitHub directly at present. Please use a proxy _(and properly configure it in the terminal)_ or just use SSH

**Comment by Jint-lzxy** [comment] 2023-02-05 04:22
Format:
```sh
export https_proxy="http://<your-address>:<your-port>"
export http_proxy="http://<your-address>:<your-port>"
# <optional> export all_proxy="socks5://<your-address>:<your-port>"
```

**Comment by Superman-wc** [comment] 2023-02-05 04:39
git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git /Users/superman/.local/share/nvim/site/lazy/lazy.nvim

This command can be executed normally in the shell alone

**Comment by Superman-wc** [comment] 2023-02-05 04:49
<img width="629" alt="image" src="https://user-images.githubusercontent.com/11311755/216802166-00f9dc51-679c-452c-859b-73ab06d1928a.png">

**Comment by Jint-lzxy** [comment] 2023-02-05 04:49
Then you may start using this config 👍 You manually performed the last step of bootstrap.

See also [Wiki: Prerequisites](https://github.com/ayamir/nvimdots/wiki/Prerequisites). You need to install some executables for full functionality, specifically:
```console
lazygit zoxide ripgrep sqlite3 fd yarn llvm go
```

Also remember to use a patched font. See: https://github.com/ayamir/nvimdots/issues/434#issuecomment-1401600103

**Comment by Jint-lzxy** [comment] 2023-02-05 04:50
> <img alt="image" width="629" src="https://user-images.githubusercontent.com/11311755/216802166-00f9dc51-679c-452c-859b-73ab06d1928a.png">

```shell
killall nvim
```

**Comment by Superman-wc** [comment] 2023-02-05 05:01
This process has been killed

**Comment by Jint-lzxy** [comment] 2023-02-05 05:07
It is probably related to some plugins / servers. If this happens again next time, please open an issue in their repo _(look for child processes)_. `nvim` itself won't use such a large amount of memory _(unless a large file is opened)_

**Comment by Jint-lzxy** [comment] 2023-02-05 05:07
Looks like the original issue has been resolved. Gonna close this one now.

If you have any further questions, feel free to reopen this at any time 👍

**Closed by Jint-lzxy** 2023-02-05 05:07 UTC
Labels: duplicate, invalid:install

**Comment by Superman-wc** [comment] 2023-02-05 05:10
<img width="791" alt="image" src="https://user-images.githubusercontent.com/11311755/216802850-990a8c76-6501-4358-8869-1d76686e9a14.png">

icon ???

**Comment by Jint-lzxy** [comment] 2023-02-05 05:12
> Also remember to use a patched font. See: https://github.com/ayamir/nvimdots/issues/434#issuecomment-1401600103.

Please follow the instructions to install a patched font.
